config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :tickets do
    resources :comments
    collection do
      get :express
    end
  end
  
  root 'tickets#index'
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base  
  belongs_to :user
  belongs_to :assignee, class_name: 'User'
  has_many :comments, as: :commentable
  
 # validates_presence_of :status, 
  
  before_create :ticket_number
  before_save :fill_in_subject
  
  # Ticket states
  def self.open
    where.not(status: 6)
  end
  
  def self.closed
    where(status: 6)
  end
  
  def self.severe
    where("priority = 3 OR priority = 4")
  end
  
  def self.assigned(user)
    where(assignee_id: user)
  end

  def self.priority
    {
      1 => 'Low',
      2 => 'Medium',
      3 => 'High',
      4 => 'Critical' 
    }
  end
  
  def self.status 
    {
      1 => 'New',
      2 => 'Dispatched',
      3 => 'In Progress',
      4 => 'Escalated',
      5 => 'Waiting',
      6 => 'Complete'
    }
  end
  
  # Ticket numbers
  def ticket_number
    d = Time.now.strftime('%m%d%y')
    if Ticket.count == 0
      n = 1
    else
      t = Ticket.last.number
      t[1..6] != d ? n = 1 : n = t[8..10].to_i + 1
    end
    self.number = 'T'+d+'.'+sprintf('%03d', n)
  end
  
  # Ticket shortcuts
  def fill_in_subject
    if self.subject.blank?
      self.subject = self.content.truncate_words(15)
    end
  end
  
  # Scopes
  scope :by_assignee_id, -> (assignee_id) {
    !assignee_id.nil? ? where(
      assignee_id: assignee_id
      ) : all
    }
  
  scope :by_user_id, -> (user_id) {
    !user_id.nil? ? where(
      user_id: user_id
      ) : all
    }
  
  scope :by_priority, -> (priority) {
    if !priority.nil? 
      if priority == 'severe'
        where("priority = 3 OR priority = 4")
      else
        where(priority: priority)
      end
    else
      all
    end
    }
  
  scope :by_status, -> (status) {
    if !status.nil?
      if status == 'open'
        where.not(status: 6)
      elsif status == 'closed'
        where(status: 6)
      else
        where(status: status)
      end
    else
      all
    end
  }
  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.order(:number).reverse_order
    
    @tickets = @tickets.by_user_id(params[:user])
      .by_assignee_id(params[:assignee])
      .by_priority(params[:priority])
      .by_status(params[:status])
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @commentable = @ticket
    @comments = @commentable.comments.order(:created_at).reverse_order
    @comment = Comment.new
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end
  
  # GET /tickets/express
  def express
    @ticket = Ticket.new
    
    @ticket.status   = 1 # New
    @ticket.priority = 2 # Medium
    @ticket.user_id  = current_user.id
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user_id = current_user.id
    
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to tickets_url, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:subject, :content, :status, :priority, :user_id, :assignee_id, :comment)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
  
  def express_ticket?
    if action_name == 'express'
      'hidden'
    else
      'string'
    end
  end
  
end

app/views/tickets/_form.html.erb
<%= simple_form_for(@ticket) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :subject, 
        as: express_ticket? %>
    
    <%= f.input :content %>
    
    <%= f.input :status, 
        collection: select('status'), 
        as: express_ticket? %>
    
    <%= f.input :priority, 
        collection: select('priority'), 
        as: express_ticket? %>
    
    <%= f.input :assignee_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/tickets/_show.html.erb
<h3>Ticket <small><strong><%= j @ticket.number %></strong></small></h3>

<div class="row">
  <div class="col-md-9">
    <h4><%= @ticket.subject %></h4>
    <p><%= @ticket.content %></p>
    <%= render "comments/comments" %>
  </div>
  <div class="col-md-3 left-border">
    <p><label>Created by:</label><strong><%= @ticket.user.username %></strong></p>
    <p>Assigned to: <strong><%= @ticket.assignee.username %></strong></p>
    <hr>
    <p><%= labels('status', @ticket) %></p>
    <p><%= labels('priority', @ticket) %></p>
    <hr>
    <p><%= link_to 'Edit Ticket', edit_ticket_path(@ticket), class: 'btn btn-default' %></p>
  </div>
</div>

app/views/tickets/edit.html.erb
<h2>Edit Ticket <small><%= @ticket.number %></small></h2>

<%= render 'form' %>

app/views/tickets/express.html.erb
<h2>Create Express Ticket</h2>

<%= render 'form' %>

app/views/tickets/index.html.erb
<%= bootstrap_modal('','') %>

<h2 class="pull-left">Listing Tickets</h2>

<div class="page-tools">
  <div class="btn-group pull-right">
    <%= link_to 'Create Ticket', express_tickets_path, 
        class: 'btn btn-primary', type: 'button', id: "modal_path" %>
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="caret"></span>
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'New Express Ticket', express_tickets_path %></li>
      <li><%= link_to 'New Advanced Ticket', new_ticket_path %></li>
    </ul>
  </div>
</div>

<div class="clearfix"></div>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">.</div>
  <table class="table">
    <thead>
      <tr>
        <th>Ticket Number</th>
        <th>Subject</th>
        <th>Status</th>
        <th>Priority</th>
        <th>Assigned to</th>
        <th>Last Updated</th>
        <th>Ticket age</th>
      </tr>
    </thead>

    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <td><%= two_part_number(ticket.number) %></td>
          <td><%= link_to ticket.subject, ticket, remote: true, data: { toggle: 'modal', target: '#modal-display' } %></td>
          <td>
            <%= link_to tickets_path(status: ticket.status) do %>
              <%= labels('status', ticket) %>
            <% end %>
          </td>
          <td>
            <%= link_to tickets_path(priority: ticket.priority) do %>
              <%= labels('priority', ticket) %>
            <% end %>
          </td>
          <td><%= ticket.assignee.username %></td>
          <td><%= time_ago_in_words(ticket.updated_at) %> ago</td>
          <td><%= time_ago_in_words(ticket.created_at) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tickets/new.html.erb
<h2>Create New Ticket</h2>

<%= render 'form' %>

app/views/tickets/show.html.erb
<%= render 'show' %>

app/views/tickets/show.js.erb
$(".modal-body").html("<%= j render 'show' %>");
$('#modal-display').modal('show');